background_image:
  type: string
  default: default
  description: Enter image url or variable from "Uploads" section above

tile_background: true

no_background:
  type: bool
  default: false
  description:
    en: Set no background image. (Will ignore background_image and tile_background settings)
